### PR TITLE
Migrate to Spine v0.7.0

### PR DESCRIPTION
**Pull request by dmdashenkov**
- Migrated to the latest release version of Spine core
 - Increased test consistency wait time

### CODE REVIEW

**Comment by dmdashenkov** [comment]
@armiol PTAL

**Comment by armiol** [comment]
@dmdashenkov let's fix the issues in the production code (i.e. in `main`) that Codacy has revealed.

**Comment by dmdashenkov** [comment]
@armiol PTAL,
also, let's discuss local testing issues.

**Comment by armiol** [comment]
@dmdashenkov LGTM.

**Review by armiol — APPROVED** [review]

**Pull request merged**
