### PR TITLE
Maven auto publishing

### PR DESCRIPTION
**Pull request by dmdashenkov**
__Note:__ Since we can't run our tests yet, I used `./gradlew assemble`.
As soon as tests can be run remotely, we should start using `./gradlew build` for `script` section in the Travis config.

### CODE REVIEW

**Comment by dmdashenkov** [comment]
@armiol PTAL

**Comment by armiol** [comment]
@dmdashenkov could you please resolve the conflict in `.travis.yml`?

**Comment by dmdashenkov** [comment]
@armiol PTAL again

**Comment by dmdashenkov** [comment]
@armiol Now automatic merging is broken again. I'll fix this as soon as `new-datastore-api` Travis build runs successfully.

**Review by armiol — APPROVED** [review]
@dmdashenkov LGTM.

**Pull request merged**
